# Generated by Django 4.2.7 on 2023-12-01 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_emotion_song_emotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='lyric',
            name='language',
            field=models.TextField(default='No Language specified', max_length=255),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='user_type',
            field=models.CharField(choices=[('standard', 'Standard User'), ('artist', 'Artist'), ('admin', 'Administrator'), ('staff', 'Staff')], default='standard', max_length=10),
        ),
        migrations.AlterField(
            model_name='song',
            name='bio',
            field=models.TextField(blank=True, max_length=450, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Restrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ban', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
