# Generated by Django 4.2.7 on 2023-12-04 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_lyric_language_alter_customusermodel_user_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
