# Generated by Django 4.2.7 on 2023-12-04 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_song_audio_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='srctype',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
