# Generated by Django 4.2.7 on 2023-12-07 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_customusermodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='User_images/'),
        ),
    ]
